### ISSUE TITLE
Bug in writeToGattCharacteristic and  byte[] message

### ISSUE THREAD

**Issue by LukaszSolo** [Velorexe/Unity-Android-Bluetooth-Low-Energy-Java-Library#2]
Hi,

Skimming tru code I noticed you probably (just skimming) a copypaste error here

https://github.com/Velorexe/Unity-Android-Bluetooth-Low-Energy-Java-Library/blob/c7cc12e6961a026045a755d5d7a479db4a30dd7b/com/velorexe/unityandroidble/UnityAndroidBLE.java#L504

(not sure if Unity version will have jar with that problem)

**Comment by Velorexe** [comment]
Wow, great catch! That indeed shouldn't be there.
I'll push a fix soon and update the Unity variant, thanks for letting me know!
