### ISSUE TITLE
Hardcoded characteristic UUID

### ISSUE THREAD

**Issue by Levieck** [Velorexe/Unity-Android-Bluetooth-Low-Energy-Java-Library#3]
Hi,

The csc characteristic on my smart trainer is 00002a5b-0000-1000-8000-00805f9b34fb (short UUID: 2a5b)
And the service UUID is:00001816-0000-1000-8000-00805f9b34fb 

For this reason, the hardcoded UUID suffix and prefix in the UnityAndroidBLE class doesn't work for me, when I tried to use it from Unity, via your Unity-Android-Bluetooth-Low-Energy project.

What do you think about extending the functions to be able to work with long UUIDs as well.
For example,  when the UUIDs are given this way:
```_readFromCharacteristic = new ReadFromCharacteristic(_deviceUuid, "00001816-0000-1000-8000-00805f9b34fb", "00002a5b-0000-1000-8000-00805f9b34fb", (byte[] value) =>```

In this case it would be great to avoid hardcoded prefixes and suffixes

**Comment by Velorexe** [comment]
Hi Levieck,

The library does support custom (long) UUID's. What you have to do is pass along a `true` boolean to the constructor and you should be good. In the library that's called a `customGatt`.

So for your read that'd be:
```cs
_readFromCharacteristic = new ReadFromCharacteristic(
   _deviceUuid,
   "00001816-0000-1000-8000-00805f9b34fb",
   "00002a5b-0000-1000-8000-00805f9b34fb",
   (byte[] value) =>{ },
   customGatt: true);
```

As you can see from this method in the Library:
https://github.com/Velorexe/Unity-Android-Bluetooth-Low-Energy-Java-Library/blob/main/com/velorexe/unityandroidble/UnityAndroidBLE.java#L480

If I misunderstood your question, be sure to let me know! I'll take another look at it then.

**Comment by Velorexe** [comment]
Hi @Levieck ,

Is this issue still occuring in your project? If so I'll keep the issue open, if not I'll close it soon!

**Comment by Levieck** [comment]
Hi,

I got what I wanted, thank you for your help.
