### ISSUE TITLE
Use Main or Develop branch?

### ISSUE THREAD

**Issue by fthiemer** [Velorexe/Unity-Android-Bluetooth-Low-Energy-Java-Library#4]
Hi Velorexe,

for my masters thesis I want to add functionality from the [polar sdk](https://github.com/polarofficial/polar-ble-sdk) to the java library and your plugin, to use it for a combination project of Unity VR and physiological data, but after having a more detailed look at the two branches I am really confused, which branch is better suited for adding to the code: 
- Main seems to be better documented and holds more functions + checks
- Develop was edited by you 2 weeks ago and includes the structure for building the app

If sb could help me with the decision that would be great!

Thanks in advance

**Comment by Velorexe** [comment]
Hiya, `main` is pretty solid one to use. Like you said, `main` is solid, as it's had more use and more time to buff out issues. `develop` is experimental, but has (in my opinion) an easier to use API, but has had no real use as of yet. We'll continue to support the `main` and `develop` branch, so in terms of support you won't need to worry.

The `develop` branch is meant for the `refactor/project-overhaul` branch of the C#/plugin repository, the `main`...well.. for `main`, so it'd also depend on the plugin version you'r using.

Hope I was able to answer your question.

**Comment by fthiemer** [comment]
Hi David, thank you for the quick answer! Especially the connection to the Unity-Plugin Branches were valuable information! 
I decided to start using the develop branch, as it contained the whole android project and I already worked on it :D 
I will be busy with adding the Polar SDK features first, so I guess it does not make a big difference. 

Hope you have a great new year!
